apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: standard
type: Opaque
data:
  POSTGRES_PASSWORD: cGFzc3dvcmQ=
  POSTGRES_USER: YWRtaW4=
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: standard
data:
  POSTGRES_DB: storedb
  POSTGRES_HOST_AUTH_METHOD: trust
