apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: helm
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.postgres.image.repository }}:{{ .Values.postgres.image.tag }}"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: {{ .Values.postgres.postgresDb }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: POSTGRES_HOST_AUTH_METHOD
              value: {{ .Values.postgres.postgresHostAuthMethod }}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data/
              name: postgres-data
          imagePullPolicy: {{ .Values.postgres.pullPolicy }}
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-data