apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: helm
  labels:
    app: postgres
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi