apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: helm
type: Opaque
data:
  POSTGRES_PASSWORD: {{ .Values.postgres.postgresPassword | b64enc }}
  POSTGRES_USER: {{ .Values.postgres.postgresUser | b64enc }}
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: helm
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: {{ .Values.pgadmin.pgadminDefaultEmail | b64enc }}
  PGADMIN_DEFAULT_PASSWORD: {{ .Values.pgadmin.pgadminDefaultPassword | b64enc }}