apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: helm
  labels:
    app: fastapi
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: fastapi
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin
  namespace: helm
  labels:
    app: pgadmin
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  selector:
    app: pgadmin
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: helm
  labels:
    app: postgres
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgres